problem1:
  m: 8

problem2:
  # machine1: [1, 3, 5, 7, 4, 2, 8, 4, 9, 9]
  machine1: [1, 3, 5, 7, 4, 2, 8, 4, 9, 9]
  machine2: [1.5, 2, 6, 8, 2, 1, 3, 8, 11, 4]

problem3:
  n: 987864561319123 
  k: 3

problem4:
  sudoko: [[0, 0, 4, 0, 0, 8, 3, 0, 0],
           [3, 0, 0, 4, 9, 1, 0, 0, 0],
           [2, 0, 0, 7, 3, 0, 0, 0, 9],
           [0, 0, 0, 0, 1, 9, 0, 6, 2],
           [0, 7, 2, 6, 0, 3, 8, 9, 0],
           [9, 6, 0, 8, 2, 0, 0, 0, 0],
           [4, 0, 0, 0, 8, 2, 0, 0, 7],
           [0, 0, 0, 3, 7, 4, 0, 0, 6],
           [0, 0, 8, 9, 0, 0, 4, 0, 0]]
  # sudoko: [[0, 0, 0, 0, 0, 0, 0, 0, 0],
  #          [0, 0, 0, 0, 0, 0, 0, 0, 0],
  #          [0, 0, 0, 0, 0, 0, 0, 0, 0],
  #          [0, 0, 0, 0, 0, 0, 0, 0, 0],
  #          [0, 0, 0, 0, 0, 0, 0, 0, 0],
  #          [0, 0, 0, 0, 0, 0, 0, 0, 0],
  #          [0, 0, 0, 0, 0, 0, 0, 0, 0],
  #          [0, 0, 0, 0, 0, 0, 0, 0, 0],
  #          [0, 0, 8, 0, 0, 0, 0, 0, 0]]